id: A428DD800
title: Prayer Recalling the Life and Liberation of the Mañjunātha Guru
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:00:58.283057
  last_modified_at: 2022-03-01 03:00:58.283060
