id: A428DD800
title: The Seeds of Faith, A Prayer to the Vidyādhara and Great Tertön Lerab Lingpa
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:00:58.301995
  last_modified_at: 2022-03-01 03:00:58.301998
