id: A428DD800
title: 'The Tambura’s Yearning Song of Devotion: A Prayer Summarizing Khandro Yeshe
  Tsogyal’s Life and Liberation'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:00:58.308458
  last_modified_at: 2022-03-01 03:00:58.308462
