id: A428DD800
title: 'The Quintessence of Marvellous Nectar: A Prayer Based on the Liberational
  Life of the Gentle Protector Guru'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:00:58.297955
  last_modified_at: 2022-03-01 03:00:58.297958
