id: A428DD800
title: A Prayer Recalling the Life and Liberation of the Precious Master Padmasambhava
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:00:58.262488
  last_modified_at: 2022-03-01 03:00:58.262491
