id: A428DD800
title: 'Cloud Banks of Blessings: A Prayer Recounting the Eleven Deeds of the Life
  and Liberation of the Guru from Uḍḍiyāna'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:00:58.272017
  last_modified_at: 2022-03-01 03:00:58.272021
