id: A428DD800
title: 'Gateway for the Faithful: A Supplication Recalling the Lives and Liberation
  of Kyabje Trulshik Rinpoche, Ngawang Chökyi Lodrö'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:00:58.277523
  last_modified_at: 2022-03-01 03:00:58.277526
