id: A428DD800
title: 'The Hook Which Invokes the Blessings: A Supplication to the Life and Liberation
  of Rigdzin Jalü Dorje'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:00:58.287306
  last_modified_at: 2022-03-01 03:00:58.287310
