id: A428DD800
title: A Prayer Recalling the Life and Liberation of the Great Perfection Adept Rangjung
  Dorje (‘Naturally Arisen Vajra’), Jigme Lingpa
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:00:58.259110
  last_modified_at: 2022-03-01 03:00:58.259115
