id: A428DD800
title: A Short Prayer Based on the Life and Liberation of the All-Knowing, All-Seeing
  Jamyang Khyentse Wangpo
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:00:58.268792
  last_modified_at: 2022-03-01 03:00:58.268795
